logging-to-file = false        # enables logging of every patch process to a seperate file
enable-magisk-update = true   # set this to false if you do not want to receive updates for the module in magisk app
build-mindetach-module = false

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

[YouTube]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
build-mode = "module"
version = "latest"
excluded-patches = "always-autorepeat copy-video-url disable-player-popup-panels disable-zoom-haptics enable-debugging external-downloads hide-autoplay-button hide-player-overlay hide-seekbar hide-timestamp hide-video-action-buttons old-video-quality-menu open-links-externally playback-speed premium-heading tablet-mini-player theme vanced-microg-support wide-searchbar"

[Tiktok]
apkmirror-dlurl = "https://apkmirror.com/apk/tiktok-pte-ltd/tik-tok-including-musical-ly/"
version = "auto"
included-patches = "hide-ads settings show-seekbar sim-spoof"
exclusive-patches = true


[Spotify]
enabled = false
uptodown-dlurl = "https://spotify.en.uptodown.com/android"
