logging-to-file = true        # enables logging of every patch process to a seperate file
enable-magisk-update = true   # set this to false if you do not want to receive updates for the module in magisk app
build-mindetach-module = false

[YouTube]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
build-mode = "module"
included-patches = "'Client spoof' 'Minimized playback' 'Remember video quality' 'Video ads' 'Hide ads' 'Swipe controls' 'Hide crowdfunding box' 'Hide info cards' 'Hide breaking news shelf' 'Hide Shorts components' 'Hide layout components' 'Hide email address' 'Spoof app version' 'Disable auto captions' 'Disable Shorts on startup' 'SponsorBlock' 'Return YouTube Dislike'"
exclusive-patches = true

[Tiktok]
apkmirror-dlurl = "https://apkmirror.com/apk/tiktok-pte-ltd/tik-tok-including-musical-ly/"
included-patches = "'SIM spoof'"
excluded-patches = "'Disable login requirement' 'Playback speed'"
exclusive-patches = true.
