logging-to-file = true        # enables logging of every patch process to a seperate file
enable-magisk-update = true   # set this to false if you do not want to receive updates for the module in magisk app
build-mindetach-module = false

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

[YouTube]
build-mode = "module"                                                   # 'both', 'apk' or 'module'
excluded-patches = "external-downloads old-video-quality-menu tablet-mini-player vanced-microg-support wide-searchbar"  # space-seperated patches to exclude (multiline strings are not supported)                                                 # space-seperated patches to exclude (multiline strings are not supported)
included-patches = ""                                                 # space-seperated patches to include (non-excluded patches are included by default)
version = "auto"                                                      # 'auto', 'latest', 'beta' or a custom one like '17.40.41'
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"

#[Twitter]
#build-mode = "apk"
#archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.twitter.android"

[TikTok]
enabled = true
#archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.zhiliaoapp.musically"
included-patches = "hide-ads settings show-seekbar sim-spoof"
archive-dlurl = "https://www.apkmirror.com/apk/tiktok-pte-ltd/tik-tok-including-musical-ly"
