name: Sync

on:
  schedule:
    - cron: '0 0 * * *'  # Run daily, adjust the schedule as needed
  workflow_dispatch:

jobs:
  sync-fork:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Git
      run: |
        git config --global user.name "${{ github.actor }}"
        git config --global user.email "${{ github.actor }}@users.noreply.github.com"
        git remote add upstream https://github.com/j-hc/revanced-magisk-module.git  

    - name: Check for changes
      id: check-sync
      run: |
        git fetch upstream
        LOCAL=$(git rev-parse @)
        REMOTE=$(git rev-parse upstream/main)
        BASE=$(git merge-base @ upstream/main)
        if [ $LOCAL = $REMOTE ]; then
          echo "Fork is already synced with upstream."
          exit 0
        fi
        if [ $LOCAL = $BASE ]; then
          echo "Local branch is behind upstream. Need to pull changes."
          exit 1
        fi
        echo "Local branch has diverged from upstream. Manual intervention may be needed."
        exit 2

    - name: Pull changes from upstream
      if: steps.check-sync.outputs.code == 1
      run: git pull upstream main

    - name: Merge changes if needed
      if: steps.check-sync.outputs.code == 2
      run: git merge --no-commit --no-ff -Xtheirs upstream/main || true
        # Exclude config file from being synchronized
        git reset HEAD config.toml || true
        git checkout -- config.toml || true
        git add -u 

    - name: Commit changes
      if: steps.check-sync.outputs.code == 2
      run: |
        git commit -m "Sync upstream changes" || echo "No changes to commit"

    - name: Push changes
      if: steps.check-sync.outputs.code == 2
      run: git push origin main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
