name: Sync

on:
  schedule:
    - cron: '0 0 * * *'  # Run daily, adjust the schedule as needed
  workflow_dispatch:

jobs:
  sync-fork:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Git
      run: |
        git config --global user.name "${{ github.actor }}"
        git config --global user.email "${{ github.actor }}@users.noreply.github.com"
        git remote add upstream https://github.com/j-hc/revanced-magisk-module.git  

    - name: Fetch upstream changes
      run: git fetch upstream

    - name: Merge changes
      run: |
        git merge --no-commit --no-ff --allow-unrelated-histories --strategy-option=ours upstream/main || true
        # Exclude config file from being synchronized
        git reset HEAD config.toml || true
        git checkout -- config.toml || true
        git add -u 

    - name: Commit changes
      run: |
        git commit -m "Sync upstream changes" || echo "No changes to commit"
